### ISSUE TITLE
Tidal & iHeart Music Support

### ISSUE THREAD

**Issue by WearifulCupid0** [SwitchbladeBot/music#12]
Tidal Api Wrapper: https://www.npmjs.com/package/korve-tidal-api-wrapper
iHeart Api Urls: 
https://api.iheart.com/api/v2/content/liveStations?q=SEARCH_QUERY
https://api.iheart.com/api/v2/content/liveStations?id=STATION_ID

No credentials are required for either.

**Comment by pedrofracassi** [comment]
That Tidal wrapper seems to be [unmaintained](https://github.com/spencercharest/tidal-api) as of July 4th

**Comment by WearifulCupid0** [comment]
This is just what it looks like, as README.md is from this dependency: https://npmjs.com/package/tidal-api-wrapper and the definitions too, but the one I sent has some modifications that left it operational again.

**Comment by pedrofracassi** [comment]
Well, the wrapper itself should be of no problem anyway. We're actually not using any wrappers for this rewrite, so it should just be a matter of using Chrome Dev Tools to find the right endpoints.

**Comment by pedrofracassi** [comment]
I had actually started on some [Tidal commands](https://github.com/SwitchbladeBot/switchblade/compare/tidal-search), which should probably be useful as a reference for whoever implements this issue.

I'll do it myself if @davipatury writes some documentation on how to add providers

**Comment by WearifulCupid0** [comment]
Ok, but how did you get a tidal api token?

As far as I know, they don't have a specific part for it, so getting a token is pretty complicated.

**Comment by WearifulCupid0** [comment]
Well, but I'm just giving you an idea, I really think it would be cool to add these 2 platforms to Switchblade.

**Comment by pedrofracassi** [comment]
> Ok, but how did you get a tidal api token?

We didn't. I scraped Tidal's web client for the endpoints and token

**Comment by davipatury** [comment]
Done 👍
