### ISSUE TITLE
A lot of music sources...

### ISSUE THREAD

**Issue by WearifulCupid0** [SwitchbladeBot/music#15]
GetYarn: Scraping HTML data. Link: https://getyarn.io

SoundClick: Scraping HTML data again... stream URL: https://www.soundclick.com/playerV5/panels/audioStream.cfm?songID=ID

Clyp: https://api.clyp.it/ID

Apple Music: https://developer.apple.com/documentation/applemusicapi/

AudioMack: https://www.audiomack.com/data-api/docs

Bandcamp: Scraping HTML data. Link: https://bandcamp.com

Vimeo: https://player.vimeo.com/video/ID/config

**Comment by pedrofracassi** [comment]
@davipatury GO GO GO

**Comment by pedrofracassi** [comment]
@WearifulCupid0 could you open an issue for each source? thanks!

**Comment by WearifulCupid0** [comment]
Okay

**Comment by WearifulCupid0** [comment]
Can I close this issue?
